export const demoProducts = [
  {
    id: "p1",
    name: "Rigorer Custom Team Jersey Set",
    requestedName: "Team uniform set",
    sku: "RIG-TEAM-JSY",
    category: "Sports Team Orders",
    moq: 25,
    distributor_price: 48,
    levelPrices: { A: 42, B: 48, C: 55 },
    stock: 640,
    status: "Available",
    aliases: [
      "team sets",
      "sets",
      "uniform sets",
      "jerseys",
      "jersey set",
      "shorts",
      "basketball uniform",
      "custom sublimation",
      "rigorer jersey",
    ],
    lead_time: "Mockup in 48h",
  },
  {
    id: "p2",
    name: "Rigorer Team Shoe Pack",
    requestedName: "Team shoes",
    sku: "RIG-SHOE-TEAM",
    category: "Sports Footwear",
    moq: 12,
    distributor_price: 74,
    levelPrices: { A: 68, B: 74, C: 82 },
    stock: 210,
    status: "Low Stock",
    aliases: [
      "team shoes",
      "shoes",
      "pairs of shoes",
      "basketball shoes",
      "AR3",
      "BP1",
      "rigorer shoes",
    ],
    lead_time: "Size run check",
  },
  {
    id: "p3",
    name: "Club Custom Hoodie and Tee Pack",
    requestedName: "Custom hoodies and shirts",
    sku: "CLUB-HOOD-TEE",
    category: "Custom Apparel",
    moq: 120,
    distributor_price: 32,
    levelPrices: { A: 28.5, B: 32, C: 36 },
    stock: 900,
    status: "Available",
    aliases: [
      "custom hoodies",
      "hoodies",
      "shirts",
      "hoodies and shirts",
      "gym merch",
      "fitness club apparel",
      "logo apparel",
    ],
    lead_time: "2 weeks after mockup",
  },
  {
    id: "p4",
    name: "Black Bottle Wholesale Case",
    requestedName: "Black bottles",
    sku: "BTL-BLK-CASE",
    category: "Wholesale Reorder",
    moq: 30,
    distributor_price: 190,
    levelPrices: { A: 175, B: 190, C: 210 },
    stock: 1100,
    status: "Available",
    aliases: [
      "black bottles",
      "black bottle",
      "black bottle cases",
      "cases of the black bottles",
      "bottle case black",
    ],
    lead_time: "Ships in 5 days",
  },
  {
    id: "p5",
    name: "White Bottle Wholesale Case",
    requestedName: "White bottles",
    sku: "BTL-WHT-CASE",
    category: "Wholesale Reorder",
    moq: 15,
    distributor_price: 188,
    levelPrices: { A: 172, B: 188, C: 208 },
    stock: 760,
    status: "Available",
    aliases: [
      "white bottles",
      "white bottle",
      "white bottle cases",
      "cases of the white ones",
      "bottle case white",
    ],
    lead_time: "Ships in 5 days",
  },
  {
    id: "p6",
    name: "Sample Kit - Apparel and Footwear",
    requestedName: "Sample kit",
    sku: "SAMPLE-APP-SHOE",
    category: "Sample Order",
    moq: 1,
    distributor_price: 95,
    levelPrices: { A: 75, B: 95, C: 120 },
    stock: 54,
    status: "Low Stock",
    aliases: ["sample kit", "samples", "sample order", "buyer samples", "fit samples"],
    lead_time: "3 business days",
  },
];

export const demoOrders = [
  {
    id: "DO-RIG-2401",
    distributor: "West Coast AAU Program",
    amount: 4750,
    status: "Submitted",
    payment: "Deposit Pending",
  },
  {
    id: "DO-GYM-2402",
    distributor: "IronPeak Fitness Club",
    amount: 6840,
    status: "Confirmed",
    payment: "Deposit Pending",
  },
  {
    id: "DO-WHOLE-2403",
    distributor: "Bright Retail Co.",
    amount: 8550,
    status: "Ready to Ship",
    payment: "Paid",
  },
];

export const demoThreads = [
  {
    id: "t1",
    type: "Missing information",
    status: "Open",
    topic: "AAU team still owes player names, jersey numbers, and exact sizes.",
    context: "DO-RIG-2401",
  },
  {
    id: "t2",
    type: "Mockup approval",
    status: "Open",
    topic: "IronPeak logo upload received; mockup approval and deposit are next.",
    context: "DO-GYM-2402",
  },
  {
    id: "t3",
    type: "Wholesale reorder",
    status: "Closed",
    topic: "Bright Retail reorder passed MOQ and shipped before the deadline.",
    context: "DO-WHOLE-2403",
  },
];
