export const demoProducts = [
  {
    id: "p1",
    name: "AeroClean Smart Air Purifier",
    requestedName: "AeroClean",
    sku: "AC-900-PRO",
    category: "Home Appliance",
    moq: 20,
    distributor_price: 119,
    levelPrices: { A: 109, B: 119, C: 132 },
    stock: 1280,
    status: "Available",
    aliases: ["aeroclean", "air purifier", "smart air purifier", "aeroclean smart air purifier"],
    lead_time: "Next week",
  },
  {
    id: "p2",
    name: "HydraGo Stainless Bottle",
    requestedName: "HydraGo Bottle",
    sku: "HG-BTL-750",
    category: "Lifestyle",
    moq: 100,
    distributor_price: 7.8,
    levelPrices: { A: 7.1, B: 7.8, C: 8.6 },
    stock: 8400,
    status: "Available",
    aliases: ["hydrago", "hydrago bottle", "stainless bottle", "bottle"],
    lead_time: "5 business days",
  },
  {
    id: "p3",
    name: "VoltMax Portable Power Bank",
    requestedName: "VoltMax Power Bank",
    sku: "VM-PB-20K",
    category: "Electronics",
    moq: 80,
    distributor_price: 19.5,
    levelPrices: { A: 17.9, B: 19.5, C: 21.25 },
    stock: 0,
    status: "Out of Stock",
    aliases: ["voltmax", "power bank", "portable power bank", "voltmax power bank"],
    lead_time: "Restock pending",
  },
  {
    id: "p4",
    name: "Lumina Desk Lamp Pro",
    requestedName: "Lumina Lamp",
    sku: "LDL-PRO-01",
    category: "Office",
    moq: 50,
    distributor_price: 31,
    levelPrices: { A: 28, B: 31, C: 34.5 },
    stock: 430,
    status: "Low Stock",
    aliases: ["lumina", "desk lamp", "lamp pro", "lumina lamp", "lumina desk lamp"],
    lead_time: "2 weeks",
  },
];

export const demoOrders = [
  { id: "DO-2026-1032", distributor: "EuroTrade GmbH", amount: 45200, status: "Ready to Ship", payment: "Paid" },
  { id: "DO-2026-1031", distributor: "Bright Retail Co.", amount: 86400, status: "Confirmed", payment: "Net 45" },
  { id: "DO-2026-1030", distributor: "ASEAN Home Supply", amount: 31900, status: "Submitted", payment: "Deposit Pending" },
];

export const demoThreads = [
  { id: "t1", type: "Order Thread", status: "Open", topic: "Can we split shipment for DO-2026-1032?", context: "DO-2026-1032" },
  { id: "t2", type: "Product Inquiry", status: "Open", topic: "Restock date for VM-PB-20K", context: "VM-PB-20K" },
];
